### ISSUE TITLE
Provide compile instructions

### ISSUE THREAD

**Issue by bkuhl** [advancedrei/BootstrapForEmail#2]
It would be nice if there were some instructions on what to do with this .less file.  My zip contains 1 .less file which references other imported .less files.  When I copy the bootstrap CSS into the template it doesn't give it hardly any visual appeal.  So I assume I'm supposed to copy bootstra-email.less, but there are no other .less files included.

**Comment by thomasvnl** [comment]
An explanation on what Less is can be found at http://lesscss.org/. Basically, Less isn't anything else (when compiled) than css but it is used to develop css stylesheets in a more efficient and faster way by using variables and functions. The source of the compiled less file won't give you any more style than the already included css because the compiled source is in fact css. Personally I think your issue isn't an issue at all in the context of this repo which was probably the reason no one replied.

If you aren't aware of how to apply the styles in the css file to your email template, please try reading the pages from Bootstrap itself which give brief examples of usage. If you aren't aware of how to apply css styles in general - I am not assuming anything - I suggest you start at learning how to apply them first before digging deeper into Bootstrap.

Good luck!

**Comment by robertmclaws** [comment]
I'm sorry, I just got busy and this post got away from me.

This project is meant to be used in conjunction with the Bootstrap LESS files to generate a set of Bootstrap styles that are roughly compatible with e-mail. You need to drop it in the Bootstrap LESS folder and have a less compiler of some kind (dotless for ASP.NET, Web Essentials for Visual Studio 2012, or whatever) to get it to pick up the Bootstrap styles and generate the CSS file. How to make all of that work is outside the scope of this project, tho I may write a blog post about it at some point.

Sorry if I couldn't me more helpful, but hopefully I pointed you in the right direction.
